import { TItemWood } from "../const/types";

export const DB_Doors_Wood: TItemWood[] = [
  {
    kind: "TItemWood",
    name: "ЛУ-21",

    id: "0001",
    material: "экошпон",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 5500,
    fullPrice: 10500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "ЛУ-22",

    id: "0002",
    material: "экошпон",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 6000, //Цена за потолно
    fullPrice: 11500,//Цена за комплект
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "A-1",
    id: "0003",
    material: "эмаль",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 9000,
    fullPrice: 14000,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      'emal'
    ],
    colors_translate: [
      'Эмаль'
    ],
  },
  {
    kind: "TItemWood",
    name: "door",
    id: "0004",
    material: "эмаль",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90004,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "door",
    id: "0005",
    material: "эмаль",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90005,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "door",
    id: "0006",
    material: "эмаль",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90006,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "door",

    id: "0007",
    material: "эмаль",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90007,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "door",

    id: "0008",
    material: "экошпон",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90008,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "door",

    id: "0009",
    material: "экошпон",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90009,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "door",

    id: "0010",
    material: "эмаль",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90010,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "door",

    id: "0011",
    material: "эмалит",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90011,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
  {
    kind: "TItemWood",
    name: "door",

    id: "0012",
    material: "натур",
    // additional : {
    //   appar: false,
    //   mirror: false,
    //   noise: false,
    //   thermal: false,
    // },

    price: 90012,
    fullPrice: 5500,
    sizes: ["600x2000", "700x2000", "800x2000", "900x2000"],
    colors: [
      "bleachedOak",
      "cappuccino",
      "darkNut",
      "gray",
      "naplesOak",
      "wenge",
    ],
    colors_translate: [
      "Беленый дуб",
      "Капучино",
      "Темный орех",
      "Серый",
      "Дуб неаполь",
      "Венге",
    ],
  },
];
